### ISSUE TITLE
Option to set-unset enable

### ISSUE THREAD

**Issue by docwhat** [sous-chefs/packagecloud#12]
Given this example:

```
packagecloud_repo "chef/stable" do
  type "rpm"
end
```

I'd like to be able to set `enable false` (like in `yum_repository`) so that it won't auto-update things (e.g. `chef-client` or `chef-server`) automatically.

**Comment by ice799** [comment]
Hi:

sorry for the delayed reply, something is up with my GitHub email notifications.

I'm not sure I totally understand what you mean by "so that it won't auto-update things" -- the `packagecloud_repo` code updates yum cache, but doesn't install any packages.

Actually, after thinking about it a bit... Is the issue you are seeing that the yum cache is updated and you have an unversioned `package "example"` that is updating the `example` package since the yum metadata has been updated?

**Comment by docwhat** [comment]
The `enabled` flag means that `yum upgrade` and `yum install` won't search that repository without the `--enablerepo` flag.

**Comment by damacus** [comment]
Sounds great. If this is something you'd be able to submit a PR for we'll accept it!
